Drop the /client prefix.

diff --git a/bin/test_docker b/bin/test_docker
--- a/bin/test_docker
+++ b/bin/test_docker
@@ -377,14 +377,14 @@ diff_body() {
 
 
 test_root_resource() {
-    echo "Testing root resource...";
+    echo "Testing VERSION.txt file...";
 
     local response="$(mktemp)";
     local    error="$(mktemp)";
 
     local e;
 
-    http_get "${host_web_port}" / > "${response}" 2> "${error}" && e=0 || e=$?;
+    http_get "${host_web_port}" /VERSION.txt > "${response}" 2> "${error}" && e=0 || e=$?;
 
     if [ ${e} -eq 22 ]; then
         fail "Root resource not found.  Expected redirect.";
@@ -406,15 +406,15 @@ test_root_resource() {
         return 1;
     fi;
 
-    local body="$(http_body < "${response}")";
-
-    if [ "${body}" != "Ranger Clubhouse Web Application" ]; then
-        fail "Unexpected body for root resource.";
-        echo "Response:"; cat "${response}";
-        return 1;
-    fi;
-
-    rm "${response}" "${error}";
+#    local body="$(http_body < "${response}")";
+#
+#    if [ "${body}" != "Ranger Clubhouse Web Application" ]; then
+#        fail "Unexpected body for root resource.";
+#        echo "Response:"; cat "${response}";
+#        return 1;
+#    fi;
+#
+#   rm "${response}" "${error}";
 }
 
 
@@ -425,7 +425,7 @@ test_app_root() {
     local     body="$(mktemp)";
     local    error="$(mktemp)";
 
-    if ! http_get "${host_web_port}" /client/ > "${response}" 2> "${error}";
+    if ! http_get "${host_web_port}" / > "${response}" 2> "${error}";
     then
         fail "Error HTTP status from server.";
         echo "Error from curl:"; cat "${error}";
